### ISSUE TITLE
Not woking With MediaType Property

### ISSUE THREAD

**Issue by hepter** [raidenyn/yandexdisk.client#11]
An error occurs because **"media_type"** went with double quotes while creating the request.
I myself have solved the problem in a primitive way but maybe you can to make a more elegant solution for other users.
**GetUrl => MvcSerializer.Serialize ();** quotes generated after generating code causes error

**Comment by raidenyn** [comment]
@hepter [Yandex.Disk docs suggest](https://tech.yandex.com/disk/api/reference/recent-upload-docpage/#format) me to use double quotes. As I remember it should work, but let me check it one more time.

**Comment by raidenyn** [comment]
Yes, you are right. It's not working with quotes now. I'll fix the request soon.

**Comment by raidenyn** [comment]
Fixed in https://github.com/raidenyn/yandexdisk.client/commit/ef598ad44d5594cacf2abbd1b2c4d7e8845e15de

Release version: [v1.3.21](https://github.com/raidenyn/yandexdisk.client/releases/tag/v1.3.21)
