### ISSUE TITLE
Why it exit directly after link1,please help

### ISSUE THREAD

**Issue by git801** [raidenyn/yandexdisk.client#14]
![23](https://user-images.githubusercontent.com/68671356/88614106-e3b68f80-d043-11ea-91af-0ac1fadab380.PNG)

Hi@raidenyn,i use your yandexdisk.client,in my opinom,it is a really wonderful project.
but i am a new one,there is something i can not understand,i beg your help,thank you so much.
Why it exit directly after link1,where i make false?

**Comment by raidenyn** [comment]
I can make a guess it's because of `GetUploadLinkAsync` method requires a valid file name, but not only a root path. 

To clarify it more I would recommend you to look at risen exceptions or/and http responses from Yandex servers.

**Comment by raidenyn** [comment]
The second guess is you don't await `UploadSample` function in external code.

**Comment by git801** [comment]
@raidenyn thank you very much,and 

> I can make a guess it's because of `GetUploadLinkAsync` method requires a valid file name, but not only a root path.
> 
> To clarify it more I would recommend you to look at risen exceptions or/and http responses from Yandex servers.

thank you very much,that is a problem for my code,i modify it,but the problem is still.

**Comment by git801** [comment]
> The second guess is you don't await `UploadSample` function in external code.

Dear sir,For asynchronous programming,i am a new one, what is the meaning of don't await UploadSample function in external code.Please.my code is all here.thank you very much.
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YandexDisk;
using YandexDisk.Client;
using YandexDisk.Client.Http;
using YandexDisk.Client.Protocol;
using System.IO;
using System.ComponentModel;
using System.Windows;
using System.Threading;

namespace yd_cli
{
    class yq
    {

        public async Task UploadSample()
        {
            Console.WriteLine("000");
            string oauthToken = "...................";

            // Create a client instance
            IDiskApi diskApi = new DiskHttpApi(oauthToken);

            //Upload file from local
            var link1 = await diskApi.Files.GetUploadLinkAsync(@"/3.txt", true,cancellationToken: CancellationToken.None);
            Console.WriteLine("111");
            //var fileName = "3.txt";
            //var destinationPath = "/";
            var content = "MyTestContent";
            var source = new MemoryStream(Encoding.UTF8.GetBytes(content));
            var size = source.Length;

            await diskApi.Files.UploadAsync(link1,source, cancellationToken: CancellationToken.None);
            //diskApi.Files.U
            /* await diskApi.Files.UploadFileAsync(path: "1.txt",
                                            overwrite: false,
                                            localFile: @"D:\1.txt",
                                            cancellationToken: CancellationToken.None);*/
            Console.WriteLine("assdfddddf");
        }


    }
    class Program
    {
        static void Main(string[] args)
        {
            // The code provided will print ‘Hello World’ to the console.
            // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
            yq yq1 = new yq();
            yq1.UploadSample();

        }
    }
}`

**Comment by git801** [comment]
> I can make a guess it's because of `GetUploadLinkAsync` method requires a valid file name, but not only a root path.
> 
> To clarify it more I would recommend you to look at risen exceptions or/and http responses from Yandex servers.

when i debug the code,it exit dieectly.

![33](https://user-images.githubusercontent.com/68671356/88629212-cdb8c700-d063-11ea-961e-cce899e8b6d0.PNG)

and "go to Definition" can not go to Definition,but to statement.

![44](https://user-images.githubusercontent.com/68671356/88629322-f5a82a80-d063-11ea-92ab-4137d781bae7.PNG)

help please,thank you so much.

**Comment by raidenyn** [comment]
Please be sure that you are using C# 7.1 or later and make the code asynchronous:

static **async Task** Main(string[] args)
    {
        // The code provided will print ‘Hello World’ to the console.
        // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
        yq yq1 = new yq();
        **await** yq1.UploadSample();
    }

**Comment by raidenyn** [comment]
I close the issue as the questions are not relative to the library.

**Comment by git801** [comment]
> I close the issue as the questions are not relative to the library.

Ok,thank you very much,best wishes to you.

**Comment by git801** [comment]
> Please be sure that you are using C# 7.1 or later and make the code asynchronous:
> 
> static **async Task** Main(string[] args)
> {
> // The code provided will print ‘Hello World’ to the console.
> // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
> yq yq1 = new yq();
> **await** yq1.UploadSample();
> }

Thank you very much,i will try it.

**Comment by git801** [comment]
Dear sir,i did what you told to me,and it is wonderful now,thank you so much for your help,best wish to you.
