### ISSUE TITLE
Is there a method for list a dirctonary on the disk?

### ISSUE THREAD

**Issue by git801** [raidenyn/yandexdisk.client#15]
Hello @raidenyn,@olegbevz,@AleksanderPushkin
Is there a method for list a dirctonary on the disk? And it returns a array,like 
a.txt
b.txt
floader1
floader2
or some others?
Thank you  very much.
Best wishes to you.

**Comment by raidenyn** [comment]
I guess `diskApi.MetaInfo.GetFilesInfoAsync` is what you are looking for. It's call [this API](https://yandex.com/dev/disk/api/reference/all-files-docpage/).
