### ISSUE TITLE
Создание папок на диске

### ISSUE THREAD

**Issue by Dims-M** [raidenyn/yandexdisk.client#16]
Здравствуйте.
Не подскажите как можно создать папку и получить на неё ссылку в яндекс диске?

**Comment by raidenyn** [comment]
You can use [`disk.Commands.CreateDictionaryAsync`](https://github.com/raidenyn/yandexdisk.client/blob/72e4f68d8ecd57e5bfde77897760104eb3a63cdb/src/YandexDisk.Client/Clients/ICommandsClient.cs#L20) for that.

**Comment by Dims-M** [comment]
Большое спасибо )))
