### ISSUE TITLE
CLI for yandexdisk.client

### ISSUE THREAD

**Issue by olegbevz** [raidenyn/yandexdisk.client#4]
Hello, 
I would like to automatically download files from Yandex.Disk using CLI. Something like this:
yadisk.exe download foo.txt C:\foo.txt
Found your implementation of yandexdisk.client on C# and it seems very usefull to me. Can I use your library to develop command line tool for Yandex.Disk?
Or perhaps you know ready command line tools.

**Comment by raidenyn** [comment]
Hi Oleg, unfortunally I don't know any exists CLI for YaDisk, but you defenetly can create the one. Would be great if you create PR in this repository, so I'll be able to help you with developing.

**Comment by raidenyn** [comment]
#5 

Created: https://www.nuget.org/packages/YandexDisk.Client.CLI/
