### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by SkyQuant** [raidenyn/yandexdisk.client#8]
После регистрации приложения у меня появились поля ID и пароль. Что из них токен, необходимый для подключения клиента?

**Comment by raidenyn** [comment]
@SkyQuant После создания приложения вы должны запросить у какого либо пользователя пустить вас на свой Диск. Путей для этого [несколько](https://tech.yandex.ru/oauth/doc/dg/concepts/about-docpage/). Только после этого у вас будет токен для доступа к Диску пользователя.
